## Phase 1: Database Schema Creation
create database if not exists my_project;
Use my_project;
# grocery-store-management

-- 1. Supplier Table
CREATE TABLE if not exists supplier (
    sup_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

select * from supplier;

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    cat_name VARCHAR(255)
);
select * from categories;

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

select * from employees;

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT AUTO_INCREMENT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);
select * from customers;

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
  

select * from products;


-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT AUTO_INCREMENT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
	 ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
     ON UPDATE CASCADE ON DELETE CASCADE
    );
select * from orders;

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from order_details;


##1. Customer Insights

## How many unique customers have placed orders?
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM orders;

## Customers with highest number of orders:
SELECT c.cust_id, c.cust_name, COUNT(o.ord_id) AS order_count
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY order_count DESC;  # if you want only top 5 customers  we can add "LIMIT 5;"

## What is the total and average purchase value per customer?

SELECT c.cust_id, c.cust_name,
       SUM(od.total_price) AS total_purchase_value,
       AVG(od.total_price) AS average_purchase_value
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase_value DESC;

## Who are the top 5 customers by total purchase amount?

SELECT c.cust_id, c.cust_name,
       SUM(od.total_price) AS total_purchase_value
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase_value DESC
LIMIT 5;

##2. Product Performance

##How many products exist in each category?

SELECT cat.cat_id, cat.cat_name, COUNT(p.prod_id) AS product_count
FROM categories cat
JOIN products p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_id, cat.cat_name
ORDER BY product_count DESC;

##What is the average price of products by category?

SELECT cat.cat_id, cat.cat_name,
       AVG(p.price) AS average_price
FROM categories cat
JOIN products p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_id, cat.cat_name
ORDER BY average_price DESC;

##Which products have the highest total sales volume (by quantity)?

SELECT p.prod_id, p.prod_name,
       SUM(od.quantity) AS total_quantity_sold
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_quantity_sold DESC;

## What is the total revenue generated by each product?

SELECT p.prod_id, p.prod_name,
       SUM(od.total_price) AS total_revenue
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_revenue DESC;

## How do product sales vary by category and supplier?

SELECT cat.cat_name,
       s.sup_name,
       SUM(od.total_price) AS total_revenue,
       SUM(od.quantity) AS total_quantity_sold
FROM order_details od
JOIN products p ON od.prod_id = p.prod_id
JOIN categories cat ON p.cat_id = cat.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
GROUP BY cat.cat_name, s.sup_name
ORDER BY total_revenue DESC;

##3. Sales and Order Trends

## How many orders have been placed in total?

SELECT COUNT(*) AS total_orders
FROM orders;

##What is the average value per order?

SELECT AVG(order_total) AS average_order_value
FROM (
    SELECT o.ord_id, SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.ord_id
) AS order_summary;

## On which dates were the most orders placed?

SELECT o.order_date, COUNT(o.ord_id) AS order_count
FROM orders o
GROUP BY o.order_date
ORDER BY order_count DESC;

##What are the monthly trends in order volume and revenue?

SELECT 
    DATE_FORMAT(STR_TO_DATE(o.order_date, '%m/%d/%Y'), '%Y-%M') AS order_month,
    COUNT(DISTINCT o.ord_id) AS total_orders,
    SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY order_month
ORDER BY order_month;

##How do order patterns vary across weekdays and weekends?

SELECT 
    DAYNAME(STR_TO_DATE(o.order_date, '%m/%d/%Y')) AS day_of_week,
    COUNT(DISTINCT o.ord_id) AS total_orders,
    SUM(od.total_price) AS total_revenue,
    CASE 
        WHEN DAYOFWEEK(STR_TO_DATE(o.order_date, '%m/%d/%Y')) IN (1,7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY day_of_week, day_type
ORDER BY FIELD(day_of_week, 'Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday');

## 4️. Supplier Contribution

## How many suppliers are there in the database?

SELECT COUNT(*) AS total_suppliers
FROM supplier;

##Which supplier provides the most products?

SELECT s.sup_id, s.sup_name,
       COUNT(p.prod_id) AS product_count
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY product_count DESC
LIMIT 1;

##What is the average price of products from each supplier?

SELECT s.sup_id, s.sup_name,
       AVG(p.price) AS average_price
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY average_price DESC;


##Which suppliers contribute the most to total product sales (by revenue)?

SELECT s.sup_id, s.sup_name,
       SUM(od.total_price) AS total_revenue
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_revenue DESC;

##5️. Employee Performance

##How many employees have processed orders?

SELECT COUNT(DISTINCT emp_id) AS employees_with_orders
FROM orders
WHERE emp_id IS NOT NULL;


##Which employees have handled the most orders?

SELECT e.emp_id, e.emp_name,
       COUNT(o.ord_id) AS orders_handled
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY orders_handled DESC;

##What is the total sales value processed by each employee?

SELECT e.emp_id, e.emp_name,
       SUM(od.total_price) AS total_sales_value
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_sales_value DESC;

## What is the average order value handled per employee?

SELECT e.emp_id, e.emp_name,
       SUM(od.total_price) / COUNT(DISTINCT o.ord_id) AS avg_order_value
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY avg_order_value DESC;

## 6️. Order Details Deep Dive

## What is the relationship between quantity ordered and total price?

SELECT quantity, total_price
FROM order_details
ORDER BY quantity;

-- This will show you the raw values. To analyze the relationship more formally:
SELECT 
    SUM(quantity) AS total_quantity,
    SUM(total_price) AS total_revenue,
    SUM(total_price) / SUM(quantity) AS avg_price_per_unit
FROM order_details;


##What is the average quantity ordered per product?

SELECT p.prod_id, p.prod_name,
       AVG(od.quantity) AS avg_quantity_ordered
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY avg_quantity_ordered DESC;

##How does the unit price vary across products and orders?

SELECT p.prod_id, p.prod_name,
       od.ord_id,
       (od.total_price / od.quantity) AS unit_price
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
WHERE od.quantity > 0
ORDER BY p.prod_id, od.ord_id;

-- Top 5 product by revenue:

SELECT 
    p.prod_id,
    p.prod_name,
    SUM(od.total_price) AS total_revenue
FROM order_details od
JOIN products p 
    ON od.prod_id = p.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_revenue DESC
LIMIT 5;

-- top 5 customers spend
SELECT 
    c.cust_id,
    c.cust_name,
    SUM(od.total_price) AS total_spent
FROM orders o
JOIN customers c 
    ON o.cust_id = c.cust_id
JOIN order_details od 
    ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_spent DESC
LIMIT 5;
